$(document).ready(function(){
    custom_language_name = "synicsray_lang";
    obj.fn.init();
    var elem = lb.queryAll("data-lang");
    for(var i=0;i<elem.length;i++){
        var data = JSON.parse($(elem[i]).attr("data-lang"));
        if(typeof(data.type)!="undefined"){
            if(data.type=="value"){
                elem[i].value = object.lang[data.page][object.language][data.value];
            }else if(data.type=="placeholder"){
                elem[i].placeholder = object.lang[data.page][object.language][data.value];
            }else if(data.type=="src"){
                elem[i].src = object.lang[data.page][object.language][data.value];
            }
        }else{
            elem[i].innerHTML = object.lang[data.page][object.language][data.value];
        }
    }

    var cookieEnabled = cookie_enable();
    if (!cookieEnabled){ //쿠키가 허용되어 있지 않으면 현재 url의 언어를 가져와서 href 경로에 붙혀준다
        if(getParameter("lang", location.href) == ""){ //lang parameter가 없으면 실행
            //사용자가 임의로 url에서 lang을 지우거나 쿠키를 허용하다가 쿠키를 허용하지 않은 경우는
            //lang parameter가 없기 때문에 기본 언어(KR)을 url에 더해준다 
            if(getParameter("param", location.href) == ""){
                location.href = location.href + "?lang=1";
            }else{
                location.href = location.href + "&lang=1";
            }
        }
        var lang = location.href.substring(location.href.length - 1 , location.href.length).toUpperCase();
        var a = document.querySelectorAll('a');
        for(var i = 0; i < a.length; i++){
            a[i].setAttribute('href', a[i].getAttribute('href') + "&lang=" + lang);
        }
    }
    if(obj.language == 1){ //한국어
        document.querySelector('html').setAttribute('lang', 'ko');
    }else if(obj.language == 2){ //영어
        document.querySelector('html').setAttribute('lang', 'en');
    }else if(obj.language == 3){ //중국어
        document.querySelector('html').setAttribute('lang', 'zh-cn');
    }

    // //console.log(obj.language);
    // set_lang(obj.language); //이 프로젝트는 class active가 없음
});

function getParameter(param, url){
    var requestParam ="";
    //현재 주소를 decoding
    var url = unescape(url);
    //파라미터만 자르고, 다시 &를 잘라서 배열에 넣는다.
    var paramArr = (url.substring(url.indexOf("?")+1,url.length)).split("&");

    for(var i = 0 ; i < paramArr.length ; i++){
        var temp = paramArr[i].split("="); //파라미터 변수명을 담음

        if(temp[0].toUpperCase() == param.toUpperCase()){
            // 변수명과 일치할 경우 데이터 삽입
            requestParam = paramArr[i].split("=")[1];
            break;
        }
    }
    return requestParam;
}

function lang_change(lang){
    //console.log(lang);
    lb.cookie({
        type:"set",
        name: custom_language_name,
        day : 3000,
        value : lang
    });
    // location.reload();
    lb.ajax({
        type:"JsonAjaxPost",
        list : {ctl:"UtilLang",param1:"change_lang",change_lang:lang},
        action:"index.php",
        havior:function(result){
            var cookieEnabled = cookie_enable();

            if (cookieEnabled){
                if(getParameter("lang", location.href) != ""){ //lang parameter가 있으면 lang parameter 제거
                    location.href = location.href.substring(0, location.href.length - 7);
                }else{
                    location.reload();
                }
            }
            else{
                if(getParameter("param", location.href) == "" || getParameter("param", location.href) == "index"){ //param값이 없으면 메인페이지로 이동
                    location.href = "http://ipia.glserver.co.kr/?lang=" + lang;
                    // location.href = "http://da.com/?lang=" + lang;
                }else{ //param 값이 있으면 현재 url에 &lang 추가
                    if(getParameter("lang", location.href) == ""){
                        location.href = location.href + "&lang=" + lang;
                    }else{
                        if(lang == "1"){
                            if(location.href.indexOf("2") != -1){
                                location.href = location.href.replace("lang=2", "lang=1");
                            }else if(location.href.indexOf("3") != -1){
                                location.href = location.href.replace("lang=3", "lang=1");
                            }
                        }else if(lang == "2"){
                            if(location.href.indexOf("1") != -1){
                                location.href = location.href.replace("lang=1", "lang=2");
                            }else if(location.href.indexOf("3") != -1){
                                location.href = location.href.replace("lang=3", "lang=2");
                            }
                        }else if(lang == "3"){
                            if(location.href.indexOf("2") != -1){
                                location.href = location.href.replace("lang=2", "lang=3");
                            }else if(location.href.indexOf("1") != -1){
                                location.href = location.href.replace("lang=1", "lang=3");
                            }
                        }
                    }
                }
            }
        }
    });
}

obj.lang = {
    "common" : {
        "1" : {
            "원" : "원",
            "삭제할 상품을 선택해주세요." : "삭제할 상품을 선택해주세요.",
            "장바구니에서 삭제하시겠습니까?" : "장바구니에서 삭제하시겠습니까?",
            "상품이 존재하지 않습니다." : "상품이 존재하지 않습니다.",
            "선택 가능 개수를 초과하였습니다." : "선택 가능 개수를 초과하였습니다.",
            "주문할 상품을 선택해주세요." : "주문할 상품을 선택해주세요.",
            "품절 상품이 포함되어있습니다." : "품절 상품이 포함되어있습니다.",
            "주문/결제" : "주문/결제",
            "배송/반품" : "배송/반품",
            "회원" : "회원",
            "기타" : "기타",
            "등록된 게시글이 없습니다." : "등록된 게시글이 없습니다.",
            "비밀글입니다." : "비밀글입니다.",
            "제목을 입력해주세요." : "제목을 입력해주세요.",
            "내용을 입력해주세요." : "내용을 입력해주세요.",
            "잠시만 기다려주세요." : "잠시만 기다려주세요.",
            "4MB 이하의 이미지 3장까지 첨부 가능" : "4MB 이하의 이미지 3장까지 첨부 가능",
            "JPG, PNG, GIF, JPEG 형식의 파일확장자" : "JPG, PNG, GIF, JPEG 형식의 파일확장자",
            "더 이상 게시글이 없습니다." : "더 이상 게시글이 없습니다.",
            "진행" : "진행",
            "마감" : "마감",
            "쿠폰을 받으시겠습니까?" : "쿠폰을 받으시겠습니까?",
            "마감된 이벤트입니다." : "마감된 이벤트입니다.",
            "쿠폰이 발급되었습니다." : "쿠폰이 발급되었습니다.",
            "쿠폰 발급기간이 종료되었습니다." : "쿠폰 발급기간이 종료되었습니다.",
            "이미 발급받은 쿠폰입니다." : "이미 발급받은 쿠폰입니다.",
            "검색어를 입력해주세요." : "검색어를 입력해주세요.",
            "제품유형별" : "제품유형별",
            "피부고민별" : "피부고민별",
            "제품라인별" : "제품라인별",
            "품절" : "품절",
            "품절된 상품입니다" : "품절된 상품입니다.",
            "로그인 후 이용 가능한 서비스입니다" : "로그인 후 이용 가능한 서비스입니다.",
            "로그인 후 이용하실 수 있습니다." : "로그인 후 이용하실 수 있습니다.",
            "쿠키를 허용하지 않으면 장바구니를 사용하실 수 없습니다.\n로그인 또는 쿠키 허용 후 사용해주세요." : "쿠키를 허용하지 않으면 장바구니를 사용하실 수 없습니다.\n로그인 또는 쿠키 허용 후 사용해주세요.",
            "옵션 선택이 필요한 상품입니다." : "옵션 선택이 필요한 상품입니다.",
            "이용약관에 동의해주세요." : "이용약관에 동의해주세요.",
            "개인정보 수집 및 이용에 동의해주세요." : "개인정보 수집 및 이용에 동의해주세요.",
            "이메일을 입력하세요" : "이메일을 입력하세요",
            "이메일 중복확인을 해주세요" : "이메일 중복확인을 해주세요",
            "비밀번호를 입력해주세요" : "비밀번호를 입력해주세요.",
            "비밀번호 확인을 입력해주세요" : "비밀번호 확인을 입력해주세요",
            "비밀번호가 일치하지 않습니다" : "비밀번호가 일치하지 않습니다",
            "영문/숫자 포함 6자 이상" : "영문/숫자 포함 6자 이상",
            "이름을 입력해주세요" : "이름을 입력해주세요",
            "전화번호 인증을 해주세요" : "전화번호 인증을 해주세요",
            "우편번호를 입력해주세요" : "우편번호를 입력해주세요",
            "상세주소를 입력해주세요" : "상세주소를 입력해주세요",
            "회원가입에 성공하셨습니다." : "회원가입에 성공하셨습니다.",
            "사용 가능한 이메일입니다." : "사용 가능한 이메일입니다.",
            "이미 가입된 이메일입니다." : "이미 가입된 이메일입니다.",
            "이미 가입된 전화번호입니다." : "이미 가입된 전화번호입니다.",
            "회원정보가 수정되었습니다." : "회원정보가 수정되었습니다.",
            "전화번호를 입력해주세요." : "전화번호를 입력해주세요.",
            "인증번호 재전송을 해주세요." : "인증번호 재전송을 해주세요.",
            "인증번호를 입력해주세요." : "인증번호를 입력해주세요.",
            "휴대폰 인증이 확인되었습니다." : "휴대폰 인증이 확인되었습니다.",
            "인증번호가 틀렸습니다." : "인증번호가 틀렸습니다.",
            "주문자명을 입력해주세요." : "주문자명을 입력해주세요.",
            "주문번호를 입력해주세요." : "주문번호를 입력해주세요.",
            "비밀번호를 입력해주세요." : "비밀번호를 입력해주세요.",
            "존재하지 않은 주문번호입니다." : "존재하지 않은 주문번호입니다.",
            "주문자명이 잘못되었습니다." : "주문자명이 잘못되었습니다.",
            "비회원 주문 비밀번호가 잘못되었습니다." : "비회원 주문 비밀번호가 잘못되었습니다.",
            "일치하는 회원정보가 없습니다." : "일치하는 회원정보가 없습니다.",
            "이메일을 입력해주세요" : "이메일을 입력해주세요",
            "일치하는 이메일이 없습니다." : "일치하는 이메일이 없습니다.",
            "입금대기" : "입금대기",
            "주문완료" : "주문완료",
            "배송준비중" : "배송준비중",
            "배송중" :  "배송중",
            "배송완료" : "배송완료",
            "취소" : "취소",
            "환불요청" : "환불요청",
            "환불확인" : "환불확인",
            "환불완료" : "환불완료",
            "교환요청" : "교환요청",
            "교환중" : "교환중",
            "교환취소" : "교환취소",
            "취소요청" : "취소요청",
            "반품요청" : "반품요청",
            "반품중" : "반품중",
            "반품완료" : "반품완료",
            "카드" : "카드",
            "실시간계좌이체" : "실시간계좌이체",
            "무통장입금" : "무통장입금",
            "신용카드" : "신용카드",
            "체크카드" : "체크카드",
            "일시불" : "일시불",
            "개월" : "개월",
            "주문을 취소하시겠습니까?" : "주문을 취소하시겠습니까?",
            "취소사유를 선택해주세요." : "취소사유를 선택해주세요.",
            "취소요청 되었습니다." : "취소요청 되었습니다.",
            "해당 상품을 반품처리하시겠습니까?" : "해당 상품을 반품처리하시겠습니까?",
            "반품요청 할 상품이 없습니다." : "반품요청 할 상품이 없습니다.",
            "반품사유를 선택해주세요." : "반품사유를 선택해주세요.",
            "반품요청 되었습니다." : "반품요청 되었습니다.",
            "반품요청을 실패했습니다." : "반품요청을 실패했습니다.",
            "해당 상품을 교환처리하시겠습니까?" : "해당 상품을 교환처리하시겠습니까?",
            "교환요청할 상품이 없습니다." : "교환요청할 상품이 없습니다.",
            "교환사유를 선택해주세요." : "교환사유를 선택해주세요.",
            "교환요청 되었습니다." : "교환요청 되었습니다.",
            "교환요청을 실패했습니다." : "교환요청을 실패했습니다.",
            "배송조회" : "배송조회",
            "미입금" : "미입금",
            "개인정보 수집 및 이용에 동의해주세요." : "개인정보 수집 및 이용에 동의해주세요.",
            "해당 게시글이 없습니다" : "해당 게시글이 없습니다",
            "관리자에게 문의해주세요" : "관리자에게 문의해주세요",
            "해당 상품이 존재하지 않습니다." : "해당 상품이 존재하지 않습니다.",
            "옵션" : "옵션",
            "옵션 선택" : "옵션 선택",
            "이미 선택된 옵션입니다." : "이미 선택된 옵션입니다.",
            "현재 상품 재고를 초과하였습니다." : "현재 상품 재고를 초과하였습니다.",
            "작성한 리뷰가 없습니다." : "작성한 리뷰가 없습니다.",
            "쿠키를 허용하지 않으면 최근 상품을 불러올 수 없습니다." : "쿠키를 허용하지 않으면 최근 상품을 불러올 수 없습니다.",
            "비회원은 쿠키를 허용하지 않으면 상품을 불러올 수 없습니다." : "비회원은 쿠키를 허용하지 않으면 상품을 불러올 수 없습니다.",
            "요청하신 주문/결제 내역이 없습니다." : "요청하신 주문/결제 내역이 없습니다.",
            "상품정보가 없습니다." : "상품정보가 없습니다.",
            "배송지정보가 초기화 됩니다. 진행하시겠습니까?" : "배송지정보가 초기화 됩니다. 진행하시겠습니까?",
            "쿠폰과 적립금은 중복사용이 불가능합니다" : "쿠폰과 적립금은 중복사용이 불가능합니다.",
            "해당 쿠폰을 적용할 수 있는 상품이 없습니다" : "해당 쿠폰을 적용할 수 있는 상품이 없습니다.",
            "포인트 사용 최소금액은 10000원 입니다." : "포인트 사용 최소금액은 10000원 입니다.",
            "3000포인트 이상부터 사용하실 수 있습니다." : "3000포인트 이상부터 사용하실 수 있습니다.",
            "포인트는 최대 10만원까지 사용가능합니다." : "포인트는 최대 10만원까지 사용가능합니다.",
            "적립금 취소" : "적립금 취소",
            "사용하려는 적립금이 총 결제금액보다 많습니다." : "사용하려는 적립금이 총 결제금액보다 많습니다.",
            "사용할 적립금을 입력해주세요" : "사용할 적립금을 입력해주세요.",
            "적립금 적용이 취소되었습니다." : "적립금 적용이 취소되었습니다.",
            "적립금 사용" : "적립금 사용",
            "쿠폰과 적립금 중복사용이 불가능합니다." : "쿠폰과 적립금 중복사용이 불가능합니다.",
            "상품리스트가 없습니다." : "상품리스트가 없습니다.",
            "비회원 비밀번호를 입력해주세요" : "비회원 비밀번호를 입력해주세요.",
            "구매자이름을 입력해주세요" : "구매자이름을 입력해주세요.",
            "구매자 휴대폰 번호를 입력해주세요" : "구매자 휴대폰 번호를 입력해주세요.",
            "구매자 이메일을 입력해주세요" : "구매자 이메일을 입력해주세요.",
            "구매자 우편번호를 입력해주세요" : "구매자 우편번호를 입력해주세요.",
            "구매자 주소를 입력해주세요" : "구매자 주소를 입력해주세요.",
            "구매자 상세 주소를 입력해주세요" : "구매자 상세 주소를 입력해주세요.",
            "배송지 정보 - 이름을 입력해주세요" : "배송지 정보 - 이름을 입력해주세요.",
            "배송지 정보 - 휴대폰번호를 입력해주세요" : "배송지 정보 - 휴대폰번호를 입력해주세요.",
            "배송지 정보 - 우편번호를 입력해주세요" : "배송지 정보 - 우편번호를 입력해주세요.",
            "배송지 정보 - 주소를 입력해주세요" : "배송지 정보 - 주소를 입력해주세요.",
            "배송지 정보 - 상세주소를 입력해주세요" : "배송지 정보 - 상세주소를 입력해주세요.",
            "결제정보를 입력해주세요" : "결제정보를 입력해주세요.",
            "현금영수증 번호를 입력해주세요" : "현금영수증 번호를 입력해주세요.",
            "구매진행에 동의해주세요." : "구매진행에 동의해주세요.",
            "결제를 실패했습니다." : "결제를 실패했습니다.",
            "총 주문금액이 일치하지 않습니다." : "총 주문금액이 일치하지 않습니다.",
            "배송비가 일치하지 않습니다." : "배송비가 일치하지 않습니다.",
            "총금액이 일치하지 않습니다." : "총금액이 일치하지 않습니다.",
            "주문번호 생성 실패하였습니다." : "주문번호 생성 실패하였습니다.",
            "등급할인 금액이 일치하지 않습니다." : "등급할인 금액이 일치하지 않습니다.",
            "쿠폰 할인 가격이 일치하지 않습니다." : "쿠폰 할인 가격이 일치하지 않습니다.",
            "쿠폰이 이미 사용되었거나 회수된 쿠폰입니다." : "쿠폰이 이미 사용되었거나 회수된 쿠폰입니다.",
            "사용적립금이 보유 적립금보다 많습니다." : "사용적립금이 보유 적립금보다 많습니다.",
            "결제후 적립금이 일치하지 않습니다." : "결제후 적립금이 일치하지 않습니다.",
            "적립금 사용 최소 포인트는 3000포인트 입니다." : "적립금 사용 최소 포인트는 3000포인트 입니다.",
            "적립금 사용 최소금액은 10000원 입니다." : "적립금 사용 최소금액은 10000원 입니다.",
            "결제방식 오류(무통장입금만 가능)입니다." : "결제방식 오류(무통장입금만 가능)입니다.",
            "쿠폰 사용이 불가능합니다." : "쿠폰 사용이 불가능합니다.",
            "쿠폰 적립금 중복사용이 불가능합니다." : "쿠폰 적립금 중복사용이 불가능합니다.",
            "주문 체크 실패" : "주문 체크 실패",
            "알림" : "알림",
            "확인" : "확인",
            "장바구니에 등록되었습니다." : "장바구니에 등록되었습니다.",
            "지금 확인하시겠습니까?" : "지금 확인하시겠습니까?",
            "네" : "네",
            "계속쇼핑" : "계속쇼핑",
            "상품 구매" : "상품 구매",
            "로그인하거나 비회원으로 구매하실 수 있습니다." : "로그인하거나 비회원으로 구매하실 수 있습니다.",
            "비회원 구매" : "비회원 구매",
            "로그인" : "로그인",
            "위시리스트에 등록되었습니다." : "위시리스트에 등록되었습니다.",
            "마이페이지에서 확인하실 수 있습니다." : "마이페이지에서 확인하실 수 있습니다.",
            "이동" : "이동",
            "이전" : "이전",
            "이미 위시리스트에 등록된 상품입니다." : "이미 위시리스트에 등록된 상품입니다.",
            "위시리스트에서 삭제되었습니다." : "위시리스트에서 삭제되었습니다.",
            "닫기" : "닫기",
            "위시리스트 등록이 취소되었습니다." : "위시리스트 등록이 취소되었습니다.",
            "미답변" : "미답변",
            "현재 비밀번호를 입력해주세요" : "현재 비밀번호를 입력해주세요.",
            "새 비밀번호를 입력해주세요" : "새 비밀번호를 입력해주세요.",
            "영문/숫자 포함 6자 이상 입력해주세요" : "영문/숫자 포함 6자 이상 입력해주세요.",
            "비밀번호가 수정되었습니다." : "비밀번호가 수정되었습니다.",
            "현재 비밀번호가 일치하지 않습니다" : "현재 비밀번호가 일치하지 않습니다.",
            "무제한" : "무제한",
            "사용가능" : "사용가능",
            "사용완료" : "사용완료",
            "회수됨" : "회수됨",
            "완료" : "완료",
            "리뷰등록" : "리뷰등록",
            "리뷰수정" : "리뷰수정",
            "수정" : "수정",
            "삭제" : "삭제",
            "적립금이 " : "적립금이 ",
            "원 사용되었습니다." : "원 사용되었습니다.",
            "적립금 사용후 최소 결제금액은 " : "적립금 사용후 최소 결제금액은 ",
            "입니다." : "입니다.",
            "사용가능 적립금은 KRW " : "사용가능 적립금은 KRW ",
            " 입니다." : " 입니다.",
            "입금자명을 입력해주세요" : "입금자명을 입력해주세요.",
            "정렬" : "정렬",
            "로그인 되지 않은 회원입니다. 로그인 후 쿠폰등록 해주세요." : "로그인 되지 않은 회원입니다. 로그인 후 쿠폰등록 해주세요.",
            "쿠폰이 등록되었습니다." : "쿠폰이 등록되었습니다.",
            "쿠폰 번호를 입력해주세요." : "쿠폰 번호를 입력해주세요.",
        },
        "2" : {
            "원" : "&#65510;",
            "삭제할 상품을 선택해주세요." : "Please select a product to delete.",
            "장바구니에서 삭제하시겠습니까?" : "Would you like to delete the selected product from the shopping cart?",
            "상품이 존재하지 않습니다." : "The product does't exist.",
            "선택 가능 개수를 초과하였습니다." : "Selectable number exceeded.",
            "주문할 상품을 선택해주세요." : "Please select a product to order.",
            "품절 상품이 포함되어있습니다." : "Includes out of stock products.",
            "주문/결제" : "Order/Payment",
            "배송/반품" : "Shipping/Return",
            "회원" : "Member",
            "기타" : "Others",
            "등록된 게시글이 없습니다." : "There are no registered posts.",
            "비밀글입니다." : "Secret Comment.",
            "제목을 입력해주세요." : "Please enter the title.",
            "내용을 입력해주세요." : "Please enter the contents.",
            "잠시만 기다려주세요." : "Wait a minute.",
            "4MB 이하의 이미지 3장까지 첨부 가능" : "Up to 3 images of 4MB or less can be attached.",
            "JPG, PNG, GIF, JPEG 형식의 파일확장자" : "File extension in JPG, PNG, GIF, JPEG format",
            "더 이상 게시글이 없습니다." : "There are no more posts.",
            "진행" : "Progress",
            "마감" : "Deadline",
            "쿠폰을 받으시겠습니까?" : "Would you like to receive a coupon?",
            "마감된 이벤트입니다." : "This is a closed event.",
            "쿠폰이 발급되었습니다." : "Coupon has been issued.",
            "쿠폰 발급기간이 종료되었습니다." : "The coupon issuance period has ended.",
            "이미 발급받은 쿠폰입니다." : "This coupon has already been issued.",
            "검색어를 입력해주세요." : "Please enter a search word.",
            "제품유형별" : "By product type",
            "피부고민별" : "By skin problem",
            "제품라인별" : "By product line",
            "품절" : "Sold out",
            "품절된 상품입니다" : "This item is out of stock.",
            "로그인 후 이용 가능한 서비스입니다" : "This page is available after login.",
            "로그인 후 이용하실 수 있습니다." : "This service is available after login.",
            "쿠키를 허용하지 않으면 장바구니를 사용하실 수 없습니다.\n로그인 또는 쿠키 허용 후 사용해주세요." : "If you do not accept cookies, you cannot use your shopping cart.\nPlease use after logging in or accepting cookies.",
            "옵션 선택이 필요한 상품입니다." : "This item requires an option.",
            "이용약관에 동의해주세요." : "Please accept the Terms and Conditions.",
            "개인정보 수집 및 이용에 동의해주세요." : "Please agree to the collection and use of personal information.",
            "이메일을 입력하세요" : "Please enter your e-mail address.",
            "이메일 중복확인을 해주세요" : "Please double check your e-mail. ",
            "비밀번호를 입력해주세요" : "Please enter the password.",
            "비밀번호 확인을 입력해주세요" : "Please enter a password confirmation.",
            "비밀번호가 일치하지 않습니다" : "Password does not match.",
            "영문/숫자 포함 6자 이상" : "Combine more than 6 characters in English/number.",
            "이름을 입력해주세요" : "Please type your name.",
            "전화번호 인증을 해주세요" : "Please verify your phone number.",
            "우편번호를 입력해주세요" : "Please enter your postal code.",
            "상세주소를 입력해주세요" : "Please enter a detailed address.",
            "회원가입에 성공하셨습니다." : "You have successfully registered as a member.",
            "사용 가능한 이메일입니다." : "The Email is available.",
            "이미 가입된 이메일입니다." : "The Email is already registered.",
            "이미 가입된 전화번호입니다." : "The phone number is already registered.",
            "회원정보가 수정되었습니다." : "Member information has been modified.",
            "전화번호를 입력해주세요." : "Please enter your phone number.",
            "인증번호 재전송을 해주세요." : "Please resend the authentication number.",
            "인증번호를 입력해주세요." : "Please enter your authentication number.",
            "휴대폰 인증이 확인되었습니다." : "Cell phone authentication has been verified.",
            "인증번호가 틀렸습니다." : "The authentication number is wrong.",
            "주문자명을 입력해주세요." : "Please enter the name of the orderer. ",
            "주문번호를 입력해주세요." : "Please enter your order number.",
            "비밀번호를 입력해주세요." : "Please enter the password.",
            "존재하지 않은 주문번호입니다." : "The order number does not exist.",
            "주문자명이 잘못되었습니다." : "The orderer name is incorrect. ",
            "비회원 주문 비밀번호가 잘못되었습니다." : "The non-member order password is incorrect.",
            "일치하는 회원정보가 없습니다." : "No member information matched.",
            "이메일을 입력해주세요" : "Please enter your email address.",
            "일치하는 이메일이 없습니다." : "No matching e-mails.",
            "입금대기" : "Waiting for Deposit",
            "주문완료" : "Order completed",
            "배송준비중" : "Preparing for delivery",
            "배송중" :  "On Delivery",
            "배송완료" : "Delivery Completed",
            "취소" : "Cancellation",
            "환불요청" : "Refund request",
            "환불확인" : "Refund confirmation",
            "환불완료" : "Refund completed",
            "교환요청" : "Exchange request",
            "교환중" : "In exchange",
            "교환취소" : "Cancellation of Exchange",
            "취소요청" : "Cancellation request",
            "반품요청" : "Return request",
            "반품중" : "In return",
            "반품완료" : "Return completed",
            "카드" : "Card",
            "실시간계좌이체" : "Real-time bank transfer",
            "무통장입금" : "Online bank transfer",
            "신용카드" : "Credit card",
            "체크카드" : "Check card",
            "일시불" : "Lump sum",
            "개월" : "months",
            "주문을 취소하시겠습니까?" : "Are you sure you want to cancel your order?",
            "취소사유를 선택해주세요." : "Please select a reason for cancellation.",
            "취소요청 되었습니다." : "Your cancellation request has been received.",
            "해당 상품을 반품처리하시겠습니까?" : "Would you like to return the product?",
            "반품요청 할 상품이 없습니다." : "There is no product to request for return.",
            "반품사유를 선택해주세요." : "Please select a reason for return.",
            "반품요청 되었습니다." : "The return application has been received.",
            "반품요청을 실패했습니다." : "The return request failed.",
            "해당 상품을 교환처리하시겠습니까?" : "Would you like to exchange the product?",
            "교환요청할 상품이 없습니다." : "교환요청할 상품이 없습니다.",
            "교환사유를 선택해주세요." : "Please select a reason for the exchange.",
            "교환요청 되었습니다." : "An application for an exchange has been received.",
            "교환요청을 실패했습니다." : "교환요청을 실패했습니다.",
            "배송조회" : "Inquiry",
            "미입금" : "Not paid",
            "개인정보 수집 및 이용에 동의해주세요." : "Please agree to the collection and use of personal information.",
            "해당 게시글이 없습니다" : "There is no corresponding post",
            "관리자에게 문의해주세요" : "Please contact the administrator",
            "해당 상품이 존재하지 않습니다." : "The product does not exist.",
            "옵션" : "Option",
            "옵션 선택" : "Select Option",
            "이미 선택된 옵션입니다." : "This option is already selected.",
            "현재 상품 재고를 초과하였습니다." : "The current product inventory has been exceeded.",
            "작성한 리뷰가 없습니다." : "There is no written review.",
            "쿠키를 허용하지 않으면 최근 상품을 불러올 수 없습니다." : "If you do not accept cookies, recent products cannot be loaded.",
            "비회원은 쿠키를 허용하지 않으면 상품을 불러올 수 없습니다." : "Non-members are not allowed to load goods unless cookies are accepted. ",
            "요청하신 주문/결제 내역이 없습니다." : "There is no order or payment history requested.",
            "상품정보가 없습니다." : "There is no product information.",
            "배송지정보가 초기화 됩니다. 진행하시겠습니까?" : "Shipping information is initialized. Would you like to proceed?",
            "쿠폰과 적립금은 중복사용이 불가능합니다" : "Coupons and reserves cannot be used in duplicate.",
            "해당 쿠폰을 적용할 수 있는 상품이 없습니다" : "There is no product the coupon can be applied to. ",
            "포인트 사용 최소금액은 10000원 입니다." : "The minimum amount of points to be used is 10,000 won.",
            "3000포인트 이상부터 사용하실 수 있습니다." : "You can use the point when it is 3,000 points or more.",
            "포인트는 최대 10만원까지 사용가능합니다." : "Points can be used up to 100,000 won.",
            "적립금 취소" : "Cancellation",
            "사용하려는 적립금이 총 결제금액보다 많습니다." : "The reserve you want to use is more than the total payment.",
            "사용할 적립금을 입력해주세요" : "Please enter the amount of reserve to use.",
            "적립금 적용이 취소되었습니다." : "Application of reserve was canceled.",
            "적립금 사용" : "Use of Reserve",
            "쿠폰과 적립금 중복사용이 불가능합니다." : "Coupons and reserves cannot be used in duplicate.",
            "상품리스트가 없습니다." : "There is no product list.",
            "비회원 비밀번호를 입력해주세요" : "Please enter a non-member password.",
            "구매자이름을 입력해주세요" : "Please enter the buyer name.",
            "구매자 휴대폰 번호를 입력해주세요" : "Please enter the buyer's mobile number.",
            "구매자 이메일을 입력해주세요" : "Please enter the buyer e-mail.",
            "구매자 우편번호를 입력해주세요" : "Please enter the buyer postal code for the delivery.",
            "구매자 주소를 입력해주세요" : "Please enter your buyer address.",
            "구매자 상세 주소를 입력해주세요" : "Please enter buyer street addres.s",
            "배송지 정보 - 이름을 입력해주세요" : "Ship To Information - Please enter your name.",
            "배송지 정보 - 휴대폰번호를 입력해주세요" : "Ship To Information - Please enter your mobile phone number.",
            "배송지 정보 - 우편번호를 입력해주세요" : "Ship To Information - Please enter your postal code.",
            "배송지 정보 - 주소를 입력해주세요" : "Ship To Information - Please enter your address.",
            "배송지 정보 - 상세주소를 입력해주세요" : "Ship To Information - Please enter a detailed address.",
            "결제정보를 입력해주세요" : "Please enter payment information.",
            "현금영수증 번호를 입력해주세요" : "Please enter the cash receipt number.",
            "구매진행에 동의해주세요." : "Please agree to purchase procedure.",
            "결제를 실패했습니다." : "Payment failed.",
            "총 주문금액이 일치하지 않습니다." : "Total order amount does not match.",
            "배송비가 일치하지 않습니다." : "Shipping cost does not match.",
            "총금액이 일치하지 않습니다." : "Total amount does not match.",
            "주문번호 생성 실패하였습니다." : "Order number creation failed.",
            "등급할인 금액이 일치하지 않습니다." : "The grade discount amount does not match.",
            "쿠폰 할인 가격이 일치하지 않습니다." : "Coupon discount price does not match.",
            "쿠폰이 이미 사용되었거나 회수된 쿠폰입니다." : "The coupon has already been used or redeemed.",
            "사용적립금이 보유 적립금보다 많습니다." : "The reserve to be used is more than the remaining reserve.",
            "결제후 적립금이 일치하지 않습니다." : "After payment, the reserve does not match.",
            "적립금 사용 최소 포인트는 3000포인트 입니다." : "You can use the point when it is 3,000 points or more.",
            "적립금 사용 최소금액은 10000원 입니다." : "The minimum amount of points to be used is 10,000 won.",
            "결제방식 오류(무통장입금만 가능)입니다." : "This is an error in payment method (Only deposit without a bankbook is possible).",
            "쿠폰 사용이 불가능합니다." : "Coupons cannot be used.",
            "쿠폰 적립금 중복사용이 불가능합니다." : "Coupons and reserves cannot be used in duplicate.",
            "주문 체크 실패" : "Order check failed. ",
            "알림" : "NOTI",
            "확인" : "Confirmed",
            "장바구니에 등록되었습니다." : "Successfully stored in your cart. Go to check right now?",
            "지금 확인하시겠습니까?" : "Would you like to check now?",
            "네" : "YES",
            "계속쇼핑" : "KEEP SHOPPING",
            "상품 구매" : "Buy Now",
            "로그인하거나 비회원으로 구매하실 수 있습니다." : "You can log in or purchase as a non-member.",
            "비회원 구매" : "Non-member Purchase",
            "로그인" : "Login",
            "위시리스트에 등록되었습니다." : "Selected item has been<br> successfully added to your wishlist.",
            "마이페이지에서 확인하실 수 있습니다." : "You can check on my page.",
            "이동" : "Move",
            "이전" : "Previous",
            "이미 위시리스트에 등록된 상품입니다." : "This item has already been added to the wish list.",
            "위시리스트에서 삭제되었습니다." : "It has been removed from your wish list.",
            "닫기" : "Close",
            "위시리스트 등록이 취소되었습니다." : "Wishlist registration canceled.",
            "미답변" : "No Answer",
            "현재 비밀번호를 입력해주세요" : "Please enter your current password.",
            "새 비밀번호를 입력해주세요" : "Please enter a new password.",
            "영문/숫자 포함 6자 이상 입력해주세요" : "Please enter at least 6 characters including English/Numeric characters.",
            "비밀번호가 수정되었습니다." : "Your password has been modified.",
            "현재 비밀번호가 일치하지 않습니다" : "The current password does not match.",
            "무제한" : "Unlimited",
            "사용가능" : "Available",
            "사용완료" : "Complete use",
            "회수됨" : "Recovered",
            "완료" : "Completion",
            "사용" : "Use",
            "적립" : "Save",
            "회수" : "Recovered",
            "리뷰등록" : "Review registration",
            "리뷰수정" : "Review Modification",
            "수정" : "Modification",
            "삭제" : "Delete",
            "적립금이 " : "",
            "원 사용되었습니다." : " has been used",
            "적립금 사용후 최소 결제금액은 " : "After using the reserve, the minimum payment amount is ",
            "입니다." : "",
            "사용가능 적립금은 KRW " : "The available points are KRW ",
            " 입니다." : "",
            "입금자명을 입력해주세요" : "Please enter the name of the depositor.",
            "정렬" : "Sort",
            "Review" : "Review",
            "Video" : "Video",
            "Exhibition" : "Exhibition",
            "로그인 되지 않은 회원입니다. 로그인 후 쿠폰등록 해주세요." : "You are not logged in. Please register for coupons after logging in.",
            "쿠폰이 등록되었습니다." : "Coupon has been registered.",
            "쿠폰 번호를 입력해주세요." : "Please enter your coupon code.",
        },
        "3" : {
            "원" : "&#65510;",
            "삭제할 상품을 선택해주세요." : "请选择要删除的商品。",
            "장바구니에서 삭제하시겠습니까?" : "您要从购物车中删除选中的商品吗？",
            "상품이 존재하지 않습니다." : "不存在该商品。",
            "선택 가능 개수를 초과하였습니다." : "超出了可选的个数。",
            "주문할 상품을 선택해주세요." : "请选择要订购的商品。",
            "품절 상품이 포함되어있습니다." : "包含断货商品。",
            "주문/결제" : "订货/付款",
            "배송/반품" : "配送/退货",
            "회원" : "会员",
            "기타" : "其他",
            "등록된 게시글이 없습니다." : "没有已发布的帖文。",
            "비밀글입니다." : "保密帖子",
            "제목을 입력해주세요." : "请输入标题。",
            "내용을 입력해주세요." : "请输入内容。",
            "잠시만 기다려주세요." : "请稍候",
            "4MB 이하의 이미지 3장까지 첨부 가능" : "最多可附3张4MB以下图片",
            "JPG, PNG, GIF 형식의 파일확장자" : "JPG、PNG、GIF、JPEG 格式文件扩展名",
            "더 이상 게시글이 없습니다." : "以下没有贴文。",
            "진행" : "进展",
            "마감" : "最后期限",
            "쿠폰을 받으시겠습니까?" : "您要获得优惠券吗?",
            "마감된 이벤트입니다." : "该活动已结束。",
            "쿠폰이 발급되었습니다." : "已成功发放优惠券。",
            "쿠폰 발급기간이 종료되었습니다." : "已过优惠券发放期限。",
            "이미 발급받은 쿠폰입니다." : "您已获得该优惠券。",
            "검색어를 입력해주세요." : "请输入搜索词。",
            "제품유형별" : "按产品类型",
            "피부고민별" : "按皮肤问题",
            "제품라인별" : "按产品线",
            "품절" : "Sold out",
            "품절된 상품입니다" : "该商品已断货。",
            "로그인 후 이용 가능한 서비스입니다" : "请先登录后，再收藏",
            "로그인 후 이용하실 수 있습니다." : "登录后方使用的服务。",
            "쿠키를 허용하지 않으면 장바구니를 사용하실 수 없습니다.\n로그인 또는 쿠키 허용 후 사용해주세요." : "如果不允许Cookie，就不能使用购物车。\n请登录或使用Cookie后再使用。",
            "옵션 선택이 필요한 상품입니다." : "需要选择选项的商品。",
            "이용약관에 동의해주세요." : "请同意服务条款。",
            "개인정보 수집 및 이용에 동의해주세요." : "请同意收集及利用个人信息。",
            "이메일을 입력하세요" : "请输入您的电子邮件",
            "이메일 중복확인을 해주세요" : "请仔细检查您的电子邮件",
            "비밀번호를 입력해주세요" : "请输入密码",
            "비밀번호 확인을 입력해주세요" : "请输入密码确认",
            "비밀번호가 일치하지 않습니다" : "密码不匹配",
            "영문/숫자 포함 6자 이상" : "请输入6位以上英文/数字",
            "이름을 입력해주세요" : "请输入名字",
            "전화번호 인증을 해주세요" : "请验证您的电话号码",
            "우편번호를 입력해주세요" : "请输入您的邮政编码",
            "상세주소를 입력해주세요" : "请输入详细地址",
            "회원가입에 성공하셨습니다." : "您已成功注册为会员。",
            "사용 가능한 이메일입니다." : "该电子邮件可用。",
            "이미 가입된 이메일입니다." : "该电子邮件已被订阅。",
            "이미 가입된 전화번호입니다." : "已加入的电话号码。",
            "회원정보가 수정되었습니다." : "会员信息已修改。",
            "전화번호를 입력해주세요." : "请输入电话号码。",
            "인증번호 재전송을 해주세요." : "请重新发送验证号。",
            "인증번호를 입력해주세요." : "请输入验证号。",
            "휴대폰 인증이 확인되었습니다." : "已成功进行手机验证。",
            "인증번호가 틀렸습니다." : "验证号错误。",
            "주문자명을 입력해주세요." : "请输入订购人姓名。",
            "주문번호를 입력해주세요." : "请输入订单号",
            "비밀번호를 입력해주세요." : "请输入密码。",
            "존재하지 않은 주문번호입니다." : "这是不存在的订单号。",
            "주문자명이 잘못되었습니다." : "订购人姓名错误。",
            "비회원 주문 비밀번호가 잘못되었습니다." : "非会员订购密码错误。",
            "일치하는 회원정보가 없습니다." : "没有匹配的会员信息。",
            "이메일을 입력해주세요" : "请输入电子邮件地址。",
            "일치하는 이메일이 없습니다." : "没有匹配的电子邮件地址。",
            "입금대기" : "等待付款",
            "주문완료" : "已成功订购",
            "배송준비중" : "正在准备配送",
            "배송중" :  "配送中",
            "배송완료" : "完成配送",
            "취소" : "取消",
            "환불요청" : "申请退款",
            "환불확인" : "确认退款",
            "환불완료" : "已成功退款",
            "교환요청" : "申请更换",
            "교환중" : "正在更换中",
            "교환취소" : "取消更换",
            "취소요청" : "申请取消",
            "반품요청" : "申请退货",
            "반품중" : "归来",
            "반품완료" : "完成退货",
            "카드" : "刷卡付款",
            "실시간계좌이체" : "实时转账",
            "무통장입금" : "无折存款",
            "신용카드" : "信用卡",
            "체크카드" : "支票卡",
            "일시불" : "一次性付款",
            "개월" : "个月",
            "주문을 취소하시겠습니까?" : "要取消订单吗？",
            "취소사유를 선택해주세요." : "请选择取消理由。",
            "취소요청 되었습니다." : "要求取消。",
            "해당 상품을 반품처리하시겠습니까?" : "要对该商品进行退货处理吗？",
            "반품요청 할 상품이 없습니다." : "没有申请退货的商品。",
            "반품사유를 선택해주세요." : "请选择退货原因。",
            "반품요청 되었습니다." : "要求退货。",
            "반품요청을 실패했습니다." : "申请退货失败",
            "해당 상품을 교환처리하시겠습니까?" : "要对该商品进行更换处理吗？", 
            "교환요청할 상품이 없습니다." : "没有申请更换的商品。", 
            "교환사유를 선택해주세요." : "请选择交换原因。", 
            "교환요청 되었습니다." : "已提出交换要求。",
            "교환요청을 실패했습니다." : "申请更换失败 ", 
            "배송조회" : "交货跟踪",
            "미입금" : "未付",
            "개인정보 수집 및 이용에 동의해주세요." : "请同意收集及利用个人信息。",
            "해당 게시글이 없습니다" : "没有该帖文。",
            "관리자에게 문의해주세요" : "请联系管理员",
            "해당 상품이 존재하지 않습니다." : "该商品不存在。",
            "옵션" : "Option",
            "옵션 선택" : "请选择选项",
            "이미 선택된 옵션입니다." : "已选中的选项。",
            "현재 상품 재고를 초과하였습니다." : "已超过目前商品库存。",
            "작성한 리뷰가 없습니다." : "没有书面评论。",
            "쿠키를 허용하지 않으면 최근 상품을 불러올 수 없습니다." : "如果不允许cookie，就无法打开最近商品。",
            "비회원은 쿠키를 허용하지 않으면 상품을 불러올 수 없습니다." : "如果非会员不允许cookie，将无法打开商品。",
            "요청하신 주문/결제 내역이 없습니다." : "没有申请的订购/付款明细。",
            "상품정보가 없습니다." : "没有产品信息。",
            "배송지정보가 초기화 됩니다. 진행하시겠습니까?" : "将重置配送地信息。还要进行吗？",
            "쿠폰과 적립금은 중복사용이 불가능합니다" : "优惠券和积分不能同时使用。",
            "해당 쿠폰을 적용할 수 있는 상품이 없습니다" : "没有可以使用该优惠券的商品。",
            "포인트 사용 최소금액은 10000원 입니다." : "可使用的最小积分为10000韩元。",
            "3000포인트 이상부터 사용하실 수 있습니다." : "3000分以上方可使用。",
            "포인트는 최대 10만원까지 사용가능합니다." : "积分最多可使用10万韩元。",
            "적립금 취소" : "取消积分",
            "사용하려는 적립금이 총 결제금액보다 많습니다." : "要使用的积分多于总付款金额。",
            "사용할 적립금을 입력해주세요" : "请输入要使用的积分。",
            "적립금 적용이 취소되었습니다." : "已成功取消积分。",
            "적립금 사용" : "使用积分",
            "쿠폰과 적립금 중복사용이 불가능합니다." : "优惠券和积分不能同时使用。",
            "상품리스트가 없습니다." : "没有产品清单。",
            "비회원 비밀번호를 입력해주세요" : "请输入非会员密码。",
            "구매자이름을 입력해주세요" : "请输入买家姓名",
            "구매자 휴대폰 번호를 입력해주세요" : "请输入买家的手机号码",
            "구매자 이메일을 입력해주세요" : "请输入买家电子邮件",
            "구매자 우편번호를 입력해주세요" : "请输入买家的邮政编码",
            "구매자 주소를 입력해주세요" : "请输入您的买家地址",
            "구매자 상세 주소를 입력해주세요" : "请输入买家的街道地址",
            "배송지 정보 - 이름을 입력해주세요" : "运送到信息 - 请输入您的名字",
            "배송지 정보 - 휴대폰번호를 입력해주세요" : "运送到信息 - 请输入您的手机号码",
            "배송지 정보 - 우편번호를 입력해주세요" : "运送到信息 - 请输入您的邮政编码",
            "배송지 정보 - 주소를 입력해주세요" : "运送到信息 - 请输入您的地址",
            "배송지 정보 - 상세주소를 입력해주세요" : "运送到信息 - 请输入详细地址",
            "결제정보를 입력해주세요" : "请输入付款信息。",
            "현금영수증 번호를 입력해주세요" : "请输入现金收据号码。",
            "구매진행에 동의해주세요." : "请同意进行购买。",
            "결제를 실패했습니다." : "付款失败",
            "총 주문금액이 일치하지 않습니다." : "订单总金额错误。",
            "배송비가 일치하지 않습니다." : "配送费错误。",
            "총금액이 일치하지 않습니다." : "总金额错误。",
            "주문번호 생성 실패하였습니다." : "创建订单号失败。",
            "등급할인 금액이 일치하지 않습니다." : "等级折扣金额错误。",
            "쿠폰 할인 가격이 일치하지 않습니다." : "优惠券折扣价格错误。",
            "쿠폰이 이미 사용되었거나 회수된 쿠폰입니다." : "已使用或已回收的优惠券。",
            "사용적립금이 보유 적립금보다 많습니다." : "使用积分多于拥有的积分。",
            "결제후 적립금이 일치하지 않습니다." : "支付后积分错误。",
            "적립금 사용 최소 포인트는 3000포인트 입니다." : "3000分以上方可使用。",
            "적립금 사용 최소금액은 10000원 입니다." : "可使用的最小积分为10000韩元。",
            "결제방식 오류(무통장입금만 가능)입니다." : "付款方式错误(只能无卡存款)。",
            "쿠폰 사용이 불가능합니다." : "不能使用优惠券。",
            "쿠폰 적립금 중복사용이 불가능합니다." : "优惠券和积分不能同时使用。",
            "주문 체크 실패" : "检查订购失败",
            "알림" : "注意",
            "확인" : "确认",
            "장바구니에 등록되었습니다." : "已添加到购物车",
            "지금 확인하시겠습니까?" : "是否要移动到购物车?",
            "네" : "购物车",
            "계속쇼핑" : "继续购物",
            "상품 구매" : "商品购买",
            "로그인하거나 비회원으로 구매하실 수 있습니다." : "登录后购物更优惠",
            "비회원 구매" : "非会员购买",
            "로그인" : "登录",
            "위시리스트에 등록되었습니다." : "所选项目已成功添加到您的愿望清单。",
            "마이페이지에서 확인하실 수 있습니다." : "您可以在我的页面上查看。",
            "이동" : "移动",
            "이전" : "以前",
            "이미 위시리스트에 등록된 상품입니다." : "此项目已被添加到愿望清单。",
            "위시리스트에서 삭제되었습니다." : "它已从您的愿望清单中删除。",
            "닫기" : "关闭",
            "위시리스트 등록이 취소되었습니다." : "Wishlist registration canceled.",
            "미답변" : "미답변",
            "현재 비밀번호를 입력해주세요" : "请输入当前密码。",
            "새 비밀번호를 입력해주세요" : "请输入新的密码。",
            "영문/숫자 포함 6자 이상 입력해주세요" : "请输入包括英文/数字的6字以上。",
            "비밀번호가 수정되었습니다." : "密码已修改。",
            "현재 비밀번호가 일치하지 않습니다" : "现在密码不一致",
            "무제한" : "无限制",
            "사용가능" : "可用的",
            "사용완료" : "使用完毕",
            "회수됨" : "被收回",
            "완료" : "完成",
            "사용" : "Use",
            "적립" : "Save",
            "회수" : "Recovered",
            "리뷰등록" : "评论注册",
            "리뷰수정" : "编辑评论",
            "수정" : "Modification",
            "삭제" : "Delete",
            "적립금이 " : "已使用",
            "원 사용되었습니다." : "韩元。",
            "적립금 사용후 최소 결제금액은 " : "使用储备金后，最低付款金额为 ",
            "입니다." : "韩元。",
            "사용가능 적립금은 KRW " : "可用储备金为",
            " 입니다." : "韩元。",
            "입금자명을 입력해주세요" : "请输入存款人的名字",
            "정렬" : "Sort",
            "Review" : "评价",
            "Video" : "视频",
            "Exhibition" : "美博会",
            "로그인 되지 않은 회원입니다. 로그인 후 쿠폰등록 해주세요." : "你没有登录。请登录后注册优惠券。",
            "쿠폰이 등록되었습니다." : "优惠券已注册。",
            "쿠폰 번호를 입력해주세요." : "请输入您的优惠券代码。",
        },
    },
}