services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Shoenet1!
      MYSQL_DATABASE: smart_shoes
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet
    command: --default-authentication-plugin=mysql_native_password --sql_mode=''

volumes:
  mysql_data:

networks:
  appnet:
    driver: bridge
